# Generated by Django 6.0 on 2025-12-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone com DDD (ex: 21999998888', max_length=20, null=True),
        ),
    ]
