# Generated by Django 6.0 on 2025-12-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jornada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
