# Generated by Django 6.0 on 2025-12-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
