# Generated by Django 6.0 on 2025-12-19 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShiftLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='attendance.workshift')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
