# Generated by Django 6.0 on 2025-12-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
