# Generated by Django 6.0 on 2025-12-19 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_workshiftlocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_type', models.CharField(choices=[('DEVICE', 'Dispositivo não autorizado'), ('LOCATION', 'Localização suspeita'), ('TIME', 'Tempo invalido'), ('MULTI_SHIFT', 'Turno duplicado'), ('TRACKING', 'Tracking inconsistente')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.workshift')),
            ],
        ),
    ]
