# Generated by Django 6.0 on 2025-12-29 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_workshift_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='adjusted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshift',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshift_adjustfments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workshift',
            name='adjusted_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshift',
            name='adjustment_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
