# Generated by Django 6.0 on 2025-12-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_fraudalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudalert',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
