# Generated by Django 6.0 on 2025-12-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_fraudalert_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudalert',
            name='score',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='severity',
            field=models.CharField(default=10, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='fraud_type',
            field=models.CharField(choices=[('DEVICE', 'Dispositivo não autorizado'), ('LOCATION', 'Localização suspeita'), ('TIME', 'Tempo invalido'), ('TRACKING', 'Tracking inconsistente'), ('MULTI_SHIFT', 'Turno duplicado')], max_length=20),
        ),
    ]
