# Generated by Django 6.0 on 2025-12-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_fraudalert_score_fraudalert_severity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudalert',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='severity',
            field=models.CharField(default='LOW', max_length=20),
        ),
    ]
